services:
  app:
    build:
      args:
        user: okhtay
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: travellist
    container_name: travellist-app    
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    restart: unless-stopped  
    networks:
      - travellist

  db:
    image: mysql:8.0
    container_name: travellist-db    
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    restart: unless-stopped  
    networks:
      - travellist

  nginx:
    image: nginx:alpine
    container_name: travellist-nginx    
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    ports:
      - 8000:80  
    restart: unless-stopped  
    networks:
      - travellist

networks:
  travellist:
    driver: bridge